version: '3.8'

services:
  ai-stream:
    build: .
    container_name: ai-stream
    ports:
      - "5500:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PYTHONUNBUFFERED=1
    volumes:
      - ./config.py:/app/config.py
      - ./.env:/app/.env
    user: "1000:1000"  # Явно указываем пользователя
    restart: unless-stopped